@echo off
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test1_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test1_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test1_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test1_4.ana"  
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test2_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test2_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test2_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test3_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test3_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test3_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test4_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test4_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test4_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test5_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test5_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test5_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test6_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test6_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test6_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test7_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test7_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test7_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test8_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test8_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test8_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test9_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test9_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test9_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test10_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test10_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test10_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test11_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test11_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test11_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test12_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test12_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test12_3.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test13_1.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test13_2.ana"
start python StatisticalMSBdata.py "C:\\Users\\yytang\\Desktop\\wav\\test13_3.ana"
echo 按任意键结束
pause
exit